# Generated by Django 4.1.3 on 2023-02-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinland_saga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='it_is_fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1_e', models.CharField(max_length=1000)),
                ('field2_p', models.CharField(max_length=10000)),
                ('captured_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='credentials',
        ),
    ]
